#!/usr/bin/env python3
"""
Stage 12B — Official Tree-Ring evaluation across repeated transitions.

Evaluates G0-G4 generated by stage12_baseline_repeated_transition.py using
the SAME official Tree-Ring inversion + eval_watermark detector previously
used for the clean/cross-checkpoint Tree-Ring experiments.

IMPORTANT
---------
Run this:
  1) inside the `tree_ring_official` conda environment
  2) from the official Tree-Ring repository directory

Default Stage-12 path:
  workspace/2/
      stage12_baseline_repeated_transition/tree_ring/manifests/

Expected manifests:
  generation_0.csv
  generation_1_flux.csv
  generation_2_realvis.csv
  generation_3_dreamshaper.csv
  generation_4_flux.csv

Outputs:
  stage12_baseline_repeated_transition/tree_ring/detection/
      repeated_transition_per_image.csv
      repeated_transition_depth_summary.csv

GPU:
  CUDA_VISIBLE_DEVICES=3
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image
from sklearn import metrics

import torch
from tqdm import tqdm

from inverse_stable_diffusion import InversableStableDiffusionPipeline
from diffusers import DPMSolverMultistepScheduler
from optim_utils import *
from io_utils import *


ROOT = Path("workspace/2")
BASELINE_ROOT = ROOT / "stage12_baseline_repeated_transition" / "tree_ring"
MANIFEST_ROOT = BASELINE_ROOT / "manifests"
OUT = BASELINE_ROOT / "detection"
OUT.mkdir(parents=True, exist_ok=True)

MODEL_ID = "sd2-community/stable-diffusion-2-1"

MANIFESTS = [
    (0, "source",       ["generation_0.csv"]),
    (1, "flux",         ["generation_1.csv", "generation_1_flux.csv"]),
    (2, "realvis",      ["generation_2.csv", "generation_2_realvis.csv"]),
    (3, "dreamshaper",  ["generation_3.csv", "generation_3_dreamshaper.csv"]),
    (4, "flux",         ["generation_4.csv", "generation_4_flux.csv"]),
]


class Args:
    # EXACT Tree-Ring settings used in our prior official reproduction.
    w_seed = 999999
    w_channel = 3
    w_pattern = "ring"
    w_mask_shape = "circle"
    w_radius = 10
    w_measurement = "l1_complex"
    w_injection = "complex"
    w_pattern_const = 0

    image_length = 512
    num_images = 1


def load_detection_pipe(device: str):
    scheduler = DPMSolverMultistepScheduler.from_pretrained(
        MODEL_ID,
        subfolder="scheduler",
    )

    # Community mirror has no fp16 revision branch.
    pipe = InversableStableDiffusionPipeline.from_pretrained(
        MODEL_ID,
        scheduler=scheduler,
        torch_dtype=torch.float16,
    )
    return pipe.to(device)


def prepare_image(path: Path, dtype, device):
    with Image.open(path) as im:
        im = im.convert("RGB")

    return (
        transform_img(im)
        .unsqueeze(0)
        .to(dtype)
        .to(device)
    )


@torch.inference_mode()
def invert_image(pipe, path, text_embeddings, device, steps):
    img = prepare_image(
        path,
        text_embeddings.dtype,
        device,
    )

    image_latents = pipe.get_image_latents(
        img,
        sample=False,
    )

    reversed_latents = pipe.forward_diffusion(
        latents=image_latents,
        text_embeddings=text_embeddings,
        guidance_scale=1,
        num_inference_steps=steps,
    )

    return reversed_latents


def condition_metrics(no_scores, w_scores, target_fpr=0.01):
    """
    Tree-Ring score = negative official distance, so larger = more watermarked.
    """
    no_scores = np.asarray(no_scores, dtype=np.float64)
    w_scores = np.asarray(w_scores, dtype=np.float64)

    scores = np.concatenate([no_scores, w_scores])
    labels = np.concatenate([
        np.zeros(len(no_scores), dtype=int),
        np.ones(len(w_scores), dtype=int),
    ])

    fpr, tpr, thresholds = metrics.roc_curve(
        labels,
        scores,
        pos_label=1,
    )

    auc = float(metrics.auc(fpr, tpr))
    acc_curve = 1.0 - (fpr + (1.0 - tpr)) / 2.0
    best_idx = int(np.argmax(acc_curve))
    best_acc = float(acc_curve[best_idx])
    best_thr = float(thresholds[best_idx])

    # Match prior Tree-Ring code: strict FPR < 1%.
    idx = np.where(fpr < target_fpr)[0]
    if len(idx):
        j = int(idx[-1])
        tpr1 = float(tpr[j])
        thr1 = float(thresholds[j])
        realized_fpr = float(fpr[j])
    else:
        tpr1 = float("nan")
        thr1 = float("nan")
        realized_fpr = float("nan")

    return {
        "roc_auc": auc,
        "best_accuracy": best_acc,
        "best_threshold": best_thr,
        "TPR_at_1pct_FPR": tpr1,
        "diagnostic_threshold_at_1pct_FPR": thr1,
        "diagnostic_realized_FPR": realized_fpr,
        "mean_unwatermarked_score": float(no_scores.mean()),
        "mean_watermarked_score": float(w_scores.mean()),
    }


def load_manifest(path: Path, limit: int | None, depth: int, generator: str):
    if not path.exists():
        raise FileNotFoundError(path)

    df = pd.read_csv(path).copy()

    # Canonical root manifests may omit metadata that is already implied by
    # the file/depth. Add it rather than rejecting otherwise valid manifests.
    if "depth" not in df.columns:
        df["depth"] = int(depth)
    if "generator" not in df.columns:
        df["generator"] = str(generator)

    required = {
        "audit_id",
        "wm_image_path",
        "alpha0_image_path",
    }
    missing = required - set(df.columns)
    if missing:
        raise RuntimeError(
            f"{path.name} missing essential columns: {sorted(missing)}; "
            f"available={list(df.columns)}"
        )

    df = df.sort_values("audit_id").copy()

    if limit is not None:
        df = df.head(limit).copy()

    # Verify all paths before starting expensive inversion.
    missing_paths = []
    for col in ["wm_image_path", "alpha0_image_path"]:
        for p in df[col].astype(str):
            if not Path(p).exists():
                missing_paths.append(p)
                if len(missing_paths) >= 10:
                    break

    if missing_paths:
        raise FileNotFoundError(
            "Missing generated images. First examples:\n"
            + "\n".join(missing_paths)
        )

    return df


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--manifest-root",
        default=str(MANIFEST_ROOT),
    )
    ap.add_argument(
        "--out-dir",
        default=str(OUT),
    )
    ap.add_argument(
        "--n",
        type=int,
        default=120,
    )
    ap.add_argument(
        "--test-num-inference-steps",
        type=int,
        default=50,
        help="Keep identical to prior official Tree-Ring detector.",
    )
    ap.add_argument(
        "--depths",
        nargs="+",
        type=int,
        default=[0, 1, 2, 3, 4],
    )
    ap.add_argument(
        "--resume",
        action="store_true",
        help="Resume from existing per-image CSV.",
    )
    args_cli = ap.parse_args()

    if not torch.cuda.is_available():
        raise RuntimeError("CUDA required.")

    device = "cuda"
    manifest_root = Path(args_cli.manifest_root)
    out = Path(args_cli.out_dir)
    out.mkdir(parents=True, exist_ok=True)

    per_image_path = out / "repeated_transition_per_image.csv"
    summary_path = out / "repeated_transition_depth_summary.csv"

    print("=" * 80)
    print("STAGE 12B — OFFICIAL TREE-RING REPEATED-TRANSITION EVALUATION")
    print("=" * 80)
    print("GPU:", torch.cuda.get_device_name(0))
    print("Detector model:", MODEL_ID)
    print("Manifest root:", manifest_root)
    print("Depths:", args_cli.depths)
    print("N per class/depth:", args_cli.n)
    print("Inversion steps:", args_cli.test_num_inference_steps)
    print()

    pipe = load_detection_pipe(device)

    # Official detector uses empty prompt during inversion.
    text_embeddings = pipe.get_text_embedding("")

    tree_args = Args()

    # Recreate exact Tree-Ring key and latent mask.
    gt_patch = get_watermarking_pattern(
        pipe,
        tree_args,
        device,
    )

    set_random_seed(0)
    dummy_latents = pipe.get_random_latents()

    watermarking_mask = get_watermarking_mask(
        dummy_latents,
        tree_args,
        device,
    )

    if args_cli.resume and per_image_path.exists():
        per_image_rows = pd.read_csv(per_image_path).to_dict("records")
        done = set(
            (int(r["depth"]), int(r["audit_id"]), str(r["class_label"]))
            for r in per_image_rows
        )
        print("Resume mode: loaded", len(per_image_rows), "existing rows.")
    else:
        per_image_rows = []
        done = set()

    manifest_map = {
        d: (name, fn)
        for d, name, fn in MANIFESTS
    }

    for depth in args_cli.depths:
        if depth not in manifest_map:
            raise ValueError(f"Unknown depth: {depth}")

        expected_name, filenames = manifest_map[depth]
        if isinstance(filenames, str):
            filenames = [filenames]
        manifest_path = next(
            (manifest_root / fn for fn in filenames if (manifest_root / fn).exists()),
            None,
        )
        if manifest_path is None:
            raise FileNotFoundError(
                f"G{depth}: none of these manifests exist under {manifest_root}: {filenames}"
            )
        df = load_manifest(manifest_path, args_cli.n, depth, expected_name)

        print("\n" + "-" * 80)
        print(
            f"G{depth}: {expected_name} | "
            f"{manifest_path.name} | rows={len(df)}"
        )
        print("-" * 80)

        for _, r in tqdm(
            df.iterrows(),
            total=len(df),
            desc=f"Tree-Ring detect G{depth}",
        ):
            aid = int(r["audit_id"])

            # Negative then positive. Each is saved immediately for resumability.
            for class_label, col in [
                ("unwatermarked", "alpha0_image_path"),
                ("watermarked", "wm_image_path"),
            ]:
                key = (depth, aid, class_label)
                if key in done:
                    continue

                img_path = Path(str(r[col]))

                reversed_latents = invert_image(
                    pipe,
                    img_path,
                    text_embeddings,
                    device,
                    args_cli.test_num_inference_steps,
                )

                # eval_watermark accepts a pair. For a single class, evaluate
                # it in both slots and take the corresponding returned metric.
                if class_label == "unwatermarked":
                    no_metric, _ = eval_watermark(
                        reversed_latents,
                        reversed_latents,
                        watermarking_mask,
                        gt_patch,
                        tree_args,
                    )
                    metric = float(no_metric)
                else:
                    _, w_metric = eval_watermark(
                        reversed_latents,
                        reversed_latents,
                        watermarking_mask,
                        gt_patch,
                        tree_args,
                    )
                    metric = float(w_metric)

                score = -metric

                per_image_rows.append({
                    "depth": depth,
                    "generator": str(r["generator"]),
                    "model_id": str(r.get("model_id", "source")),
                    "strength": float(r.get("strength", 0.0)),
                    "audit_id": aid,
                    "class_label": class_label,
                    "tree_ring_distance": metric,
                    "tree_ring_score": score,
                    "image_path": str(img_path.resolve()),
                })

                done.add(key)

                # Save after every image/class so a long inversion run is safe.
                pd.DataFrame(per_image_rows).to_csv(
                    per_image_path,
                    index=False,
                )

        # Print interim metric as soon as a depth completes.
        per = pd.DataFrame(per_image_rows)
        d = per[per["depth"] == depth]
        no_scores = d.loc[
            d["class_label"] == "unwatermarked",
            "tree_ring_score"
        ].to_numpy()
        w_scores = d.loc[
            d["class_label"] == "watermarked",
            "tree_ring_score"
        ].to_numpy()

        m = condition_metrics(no_scores, w_scores)

        print(
            f"\nG{depth} RESULT: "
            f"AUC={m['roc_auc']:.6f} | "
            f"ACC={m['best_accuracy']:.6f} | "
            f"TPR@1%FPR={m['TPR_at_1pct_FPR']:.6f}"
        )

    # Final summary.
    per = pd.DataFrame(per_image_rows)

    summary_rows = []

    for depth in sorted(args_cli.depths):
        d = per[per["depth"] == depth].copy()

        no_scores = d.loc[
            d["class_label"] == "unwatermarked",
            "tree_ring_score"
        ].to_numpy()

        w_scores = d.loc[
            d["class_label"] == "watermarked",
            "tree_ring_score"
        ].to_numpy()

        if len(no_scores) == 0 or len(w_scores) == 0:
            continue

        m = condition_metrics(no_scores, w_scores)

        first = d.iloc[0]

        summary_rows.append({
            "depth": depth,
            "generator": str(first["generator"]),
            "model_id": str(first["model_id"]),
            "strength": float(first["strength"]),
            "n_per_class": min(len(no_scores), len(w_scores)),
            **m,
        })

    summary = pd.DataFrame(summary_rows)
    summary.to_csv(summary_path, index=False)

    print("\n" + "=" * 80)
    print("FINAL TREE-RING PERSISTENCE CURVE")
    print("=" * 80)

    cols = [
        "depth",
        "generator",
        "n_per_class",
        "roc_auc",
        "TPR_at_1pct_FPR",
        "best_accuracy",
        "mean_unwatermarked_score",
        "mean_watermarked_score",
    ]
    print(summary[cols].to_string(index=False))

    print("\nSaved:")
    print(" ", per_image_path)
    print(" ", summary_path)


if __name__ == "__main__":
    main()
